package me.verma.app;

import java.util.List;

public class Utils {
    public static boolean containsChar(final String s, final char c) {
        return s.indexOf(c) != -1;
    }

    public static List<String> starters() {
        return List.of(
                "snare",
                "yuppy",
                "tears",
                "quest",
                "piano",
                "cream",
                "roate",
                "train",
                "heart",
                "irate",
                "weary",
                "canoe",
                "there",
                "those",
                "trail",
                "hasty",
                "beaus",
                "roast",
                "trash",
                "haste",
                "beach",
                "learn",
                "point",
                "sweat",
                "place",
                "stare",
                "trace",
                "fence",
                "match",
                "ouija",
                "boats",
                "alone",
                "smile",
                "reads",
                "clean",
                "trade",
                "about",
                "diner",
                "inert",
                "horse",
                "could",
                "mount",
                "store",
                "party",
                "peals",
                "horns",
                "stale",
                "ourie",
                "raise",
                "thins",
                "opera",
                "dates",
                "until",
                "house",
                "great",
                "until",
                "alive",
                "yukon",
                "aisle",
                "clear",
                "rates",
                "bread",
                "rents",
                "coats",
                "orate",
                "world",
                "teach",
                "stain",
                "alien",
                "weird",
                "first",
                "taser",
                "atone",
                "spicy",
                "heats",
                "alive",
                "aeons",
                "steal",
                "ideas",
                "water",
                "spear",
                "start",
                "quiet",
                "stead",
                "apple",
                "saint",
                "marne",
                "bacon",
                "house",
                "fight",
                "auger",
                "slate",
                "promo",
                "acted"
        );
    }

    public static void printEmphasized(Object msg) {
        System.out.println("\033[31;1;4m" + msg + "\033[0m");
    }
}
