package me.verma.app;

import java.util.List;

public class Utils {
    public static boolean containsChar(final String s, final char c) {
        return s.indexOf(c) != -1;
    }

    public static List<String> starters() {
        return List.of(
                "SNARE",
                "YUPPY",
                "TEARS",
                "QUEST",
                "PIANO",
                "CREAM",
                "ROATE",
                "TRAIN",
                "HEART",
                "IRATE",
                "WEARY",
                "CANOE",
                "THERE",
                "THOSE",
                "TRAIL",
                "HASTY",
                "BEAUS",
                "ROAST",
                "TRASH",
                "HASTE",
                "BEACH",
                "LEARN",
                "POINT",
                "SWEAT",
                "PLACE",
                "STARE",
                "TRACE",
                "FENCE",
                "MATCH",
                "OUIJA",
                "BOATS",
                "ALONE",
                "SMILE",
                "READS",
                "CLEAN",
                "TRADE",
                "ABOUT",
                "DINER",
                "INERT",
                "HORSE",
                "COULD",
                "MOUNT",
                "STORE",
                "PARTY",
                "PEALS",
                "HORNS",
                "STALE",
                "OURIE",
                "RAISE",
                "THINS",
                "OPERA",
                "DATES",
                "UNTIL",
                "HOUSE",
                "GREAT",
                "UNTIL",
                "ALIVE",
                "YUKON",
                "AISLE",
                "CLEAR",
                "RATES",
                "BREAD",
                "RENTS",
                "COATS",
                "ORATE",
                "WORLD",
                "TEACH",
                "STAIN",
                "ALIEN",
                "WEIRD",
                "FIRST",
                "TASER",
                "ATONE",
                "SPICY",
                "HEATS",
                "ALIVE",
                "AEONS",
                "STEAL",
                "IDEAS",
                "WATER",
                "SPEAR",
                "START",
                "QUIET",
                "STEAD",
                "APPLE",
                "SAINT",
                "MARNE",
                "BACON",
                "HOUSE",
                "FIGHT",
                "AUGER",
                "SLATE"
        );
    }
}
